// Sort Category
const SORT_CATEGORY = {
  DATE: 0,
  VIEW_COUNT: 1,
  LIKE_COUNT: 2,
  DISLIKE_COUNT: 3,
  DURATION: 4,
  LIKE_DISLIKE_RATE: 5,
  LIKE_DISLIKE_GAP: 6,
  VIEW_LIKE_RATE: 7,
  VIEW_LIKE_GAP: 8,
  LIKE_DURATION_RATE: 9,

  VIEW_COUNT_SUM: 100,
  VIEW_COUNT_AVG: 101,
  LIKE_COUNT_SUM: 102,
  LIKE_COUNT_AVG: 103,
  DISLIKE_COUNT_SUM: 104,
  DISLIKE_COUNT_AVG: 105,
};

// Sort Order
const SORT_ORDER = {
  ASC: 0,
  DSC: 1,
};

export {
  SORT_CATEGORY,
  SORT_ORDER,
}