// Sort Category
const SORT_CATEGORY = {
  VIEW_COUNT: 0,
  LIKE_COUNT: 1,
  DISLIKE_COUNT: 2,
  LIKE_RATE: 3,
  LIKE_GAP: 4,
  VIEW_LIKE_RATE: 5,
  VIEW_LIKE_GAP: 6,
  DATE: 7,

  VIEW_COUNT_SUM: 100,
  VIEW_COUNT_AVG: 101,
  LIKE_COUNT_SUM: 102,
  LIKE_COUNT_AVG: 103,
  DISLIKE_COUNT_SUM: 104,
  DISLIKE_COUNT_AVG: 105,
};

// Sort Order
const SORT_ORDER = {
  ASC: 0,
  DSC: 1,
};

export {
  SORT_CATEGORY,
  SORT_ORDER,
}